name: Continuous Integration #Nom du workflow
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Restore Dependencies
        run: dotnet restore ./my-first-app.csproj

      - name: Build Project
        id: build
        run: dotnet build ./my-first-app.csproj --no-restore
