name: CI - PR feature to dev

# Déclenchement UNIQUEMENT sur Pull Request vers dev
on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Restore Dependencies
        run: dotnet restore ./my-first-app.csproj

      - name: Build Project
        id: build
        run: dotnet build ./my-first-app.csproj --no-restore

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # ou la version que tu utilises
          cache: 'npm'
          cache-dependency-path: './package-lock.json'  # Si ton package-lock.json est à la racine

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  snyk-sca-critical:
    name: SCA (CRITICAL) via SNYK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Snyk SCA (CRITICAL only)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=critical

  code-format:
    name: Code Formatting (linting)
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check code format
        run: npm run format:check
      
      - name: Run linter
        run: npm run lint

  snyk-sast:
    name: SAST (HIGH/CRITICAL) via SNYK
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Snyk Code (HIGH/CRITICAL)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high
